version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  frontend:
    image: oven/bun:latest
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    working_dir: /app
    command: bun run start
    depends_on:
      - mongodb
    networks:
      - app_network

volumes:
  mongodb_data:
  frontend_modules:

networks:
  app_network:
    driver: bridge
