services:
  document_db:
    image: mongo:latest
    container_name: document_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db
      
    networks:
      - app_network
    dns:
      - 8.8.8.8
    env_file:
      - .env

  frontend:
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 3m
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - frontend_modules:/app/node_modules
    environment:
      - LOG_LEVEL=info
    depends_on:
      - document_db
    networks:
      - app_network
      
  mongodb_compass:
    image: mongo-express
    container_name: mongodb_compass
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://root:example@document_db:27017/
    depends_on:
      - document_db
    networks:
      - app_network

volumes:
  mongodb_data:
  frontend_modules:

networks:
  app_network:
    driver: bridge
