services:
  document-db:
    image: mongo:latest
    container_name: document-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db
      
    networks:
      - app_network
    dns:
      - 8.8.8.8
    env_file:
      - .env

  frontend:
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 3m
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - frontend_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=info
    depends_on:
      - document-db
    networks:
      - app_network

volumes:
  mongodb_data:
  frontend_modules:

networks:
  app_network:
    driver: bridge
